// ─── rodo-shared.js ──────────────────────────────────────────────────────────
// Єдиний модуль теми та перекладів для всього проекту Родовід.
// Підключається на кожній сторінці: import './rodo-shared.js'
// ─────────────────────────────────────────────────────────────────────────────

// ════════════════════════════════════════════════════════════════════
// ТЕМИ
// ════════════════════════════════════════════════════════════════════
export const themes = {
  forest: {
    '--bg':'#f5f0e8','--bg2':'#ede6d6','--green':'#3a6b4a',
    '--green-light':'#5a8f6a','--green-pale':'#d4e8da',
    '--brown':'#7a5c3a','--text':'#2c2218','--muted':'#7a6a55',
    '--border':'#d8cdb8','--white':'#fff',
    '--shadow':'0 8px 32px rgba(60,40,10,0.13)',
    '--red':'#c94040','--red-pale':'#fdeaea',
  },
  ocean: {
    '--bg':'#e8f2f8','--bg2':'#d8eaf4','--green':'#2a6080',
    '--green-light':'#3a80a8','--green-pale':'#c8e0ee',
    '--brown':'#3a6878','--text':'#0f2a38','--muted':'#4a7088',
    '--border':'#b8d4e4','--white':'#fff',
    '--shadow':'0 8px 32px rgba(10,40,70,0.15)',
    '--red':'#c94040','--red-pale':'#fdeaea',
  },
  autumn: {
    '--bg':'#fdf3e8','--bg2':'#f5e6d0','--green':'#a04020',
    '--green-light':'#c05030','--green-pale':'#fde0cc',
    '--brown':'#8a5020','--text':'#2a1408','--muted':'#8a5a3a',
    '--border':'#e0c8a8','--white':'#fff',
    '--shadow':'0 8px 32px rgba(80,30,10,0.14)',
    '--red':'#c94040','--red-pale':'#fdeaea',
  },
  night: {
    '--bg':'#1a1f2e','--bg2':'#141824','--green':'#4a7acf',
    '--green-light':'#6a9aef','--green-pale':'#1e2d4a',
    '--brown':'#7a8aaa','--text':'#e0e8f8','--muted':'#8090b0',
    '--border':'#2a3550','--white':'#1e2438',
    '--shadow':'0 8px 32px rgba(0,0,0,0.4)',
    '--red':'#e05555','--red-pale':'#2d1a1a',
  },
  rose: {
    '--bg':'#fdf0f0','--bg2':'#f5e2e2','--green':'#a04060',
    '--green-light':'#c05070','--green-pale':'#fde0e8',
    '--brown':'#8a4050','--text':'#280a14','--muted':'#8a4a58',
    '--border':'#e0c0c8','--white':'#fff',
    '--shadow':'0 8px 32px rgba(80,20,40,0.13)',
    '--red':'#c94040','--red-pale':'#fdeaea',
  },
  sand: {
    '--bg':'#f5f0e0','--bg2':'#ede4cc','--green':'#7a6030',
    '--green-light':'#9a7840','--green-pale':'#e8dfc0',
    '--brown':'#6a5028','--text':'#28200c','--muted':'#7a6840',
    '--border':'#d8c898','--white':'#fff',
    '--shadow':'0 8px 32px rgba(60,40,10,0.13)',
    '--red':'#c94040','--red-pale':'#fdeaea',
  },
};

/** Застосовує збережену тему до документа (CSS-змінні на :root). */
export function applyStoredTheme() {
  const saved = localStorage.getItem('rodo-theme');
  if (saved && themes[saved]) {
    Object.entries(themes[saved]).forEach(([k, v]) =>
      document.documentElement.style.setProperty(k, v)
    );
  }
}

// ════════════════════════════════════════════════════════════════════
// ПЕРЕКЛАДИ
// ════════════════════════════════════════════════════════════════════
export const i18n = {
  uk: {
    // ── Навігація (спільна) ──
    'nav.logo':       'Родо',
    'nav.logoSpan':   'від',
    'nav.back':       '← На головну',
    'nav.signin':     'Увійти',
    'nav.settings':   'Налаштування',
    'nav.myTree':     'Моє дерево',
    'nav.treeList':   'Мої дерева',

    // ── Головна (main.html) ──
    'main.heroTitle':   'Збережіть пам\'ять свого роду',
    'main.heroSub':     'Будуйте генеалогічне дерево, зберігайте фото та біографії, зв\'язуйте покоління.',
    'main.btnCreate':   '🌱 Створити дерево',
    'main.btnMyTrees':  '🌿 Мої дерева',
    'main.btnSignIn':   'Увійти',
    'main.feat1Title':  'Необмежені покоління',
    'main.feat1Desc':   'Додавайте стільки предків та нащадків, скільки потрібно.',
    'main.feat2Title':  'Хмарне збереження',
    'main.feat2Desc':   'Ваші дані завжди в безпеці та доступні з будь-якого пристрою.',
    'main.feat3Title':  'Зручний редактор',
    'main.feat3Desc':   'Перетягуйте картки, додавайте фото, встановлюйте зв\'язки.',

    // ── Вхід / реєстрація (signIn.html) ──
    'signin.tabLogin':    'Увійти',
    'signin.tabRegister': 'Реєстрація',
    'signin.loginTitle':  'З поверненням 👋',
    'signin.loginSub':    'Увійдіть, щоб продовжити роботу зі своїм деревом',
    'signin.email':       'Електронна пошта',
    'signin.password':    'Пароль',
    'signin.forgot':      'Забули пароль?',
    'signin.btnLogin':    'Увійти',
    'signin.orDivider':   'або',
    'signin.googleLogin': 'Увійти через Google',
    'signin.regTitle':    'Створити акаунт 🌱',
    'signin.regSub':      'Почніть будувати своє сімейне дерево вже сьогодні',
    'signin.name':        'Ім\'я та прізвище',
    'signin.email2':      'Електронна пошта',
    'signin.password2':   'Пароль',
    'signin.confirm':     'Підтвердіть пароль',
    'signin.btnRegister': 'Зареєструватись',
    'signin.googleReg':   'Зареєструватись через Google',
    'signin.backLink':    '← Повернутись',

    // ── Налаштування (settings.html) ──
    'nav.profile':        'Профіль',
    'nav.appearance':     'Вигляд',
    'nav.notifications':  'Сповіщення',
    'nav.privacy':        'Приватність',
    'nav.data':           'Дані',
    'nav.danger':         'Небезпечна зона',
    'page.title':         'Налаштування',
    'page.sub':           'Управляйте своїм акаунтом та персоналізуйте Родовід',
    'profile.title':      'Профіль',
    'profile.desc':       'Ваше ім\'я та особиста інформація',
    'profile.firstName':  'Ім\'я',
    'profile.lastName':   'Прізвище',
    'profile.email':      'Електронна пошта',
    'profile.bio':        'Про себе',
    'profile.dob':        'Дата народження',
    'profile.phone':      'Телефон',
    'profile.changePass': 'Змінити пароль',
    'profile.passHint':   'Залиште порожнім, якщо не хочете змінювати',
    'profile.currentPass':'Поточний пароль',
    'profile.newPass':    'Новий пароль',
    'profile.confirmPass':'Підтвердження',
    'appear.title':       'Вигляд',
    'appear.desc':        'Тема та мова інтерфейсу',
    'appear.themeLabel':  'Тема кольорів',
    'appear.langLabel':   'Мова інтерфейсу',
    'notif.title':        'Сповіщення',
    'notif.desc':         'Керуйте тим, що і як вам надходить',
    'notif.email':        'Email-сповіщення',
    'notif.emailDesc':    'Отримувати важливі оновлення на пошту',
    'notif.shared':       'Нові спільні дерева',
    'notif.sharedDesc':   'Коли хтось запрошує вас до дерева',
    'notif.changes':      'Зміни від учасників',
    'notif.changesDesc':  'Коли хтось редагує спільне дерево',
    'notif.bday':         'Нагадування про дні народження',
    'notif.bdayDesc':     'Сповіщення за день до дати народження',
    'notif.marketing':    'Маркетингові листи',
    'notif.marketingDesc':'Поради, новини та оновлення продукту',
    'priv.title':         'Приватність',
    'priv.desc':          'Контролюйте, хто що бачить',
    'priv.public':        'Публічний профіль',
    'priv.publicDesc':    'Інші користувачі можуть знайти вас у пошуку',
    'priv.showDob':       'Відображати дату народження',
    'priv.showDobDesc':   'Видимо для учасників спільних дерев',
    'priv.invites':       'Дозволити запрошення',
    'priv.invitesDesc':   'Інші можуть запрошувати вас до дерев',
    'priv.2fa':           'Двофакторна автентифікація',
    'priv.2faDesc':       'Підвищений захист акаунту',
    'priv.visibility':    'Хто може переглядати ваші дерева',
    'data.title':         'Дані та експорт',
    'data.desc':          'Управляйте своїми даними та деревами',
    'data.autosave':      'Автозбереження',
    'data.autosaveDesc':  'Автоматично зберігати зміни кожні 5 хвилин',
    'data.backup':        'Резервні копії',
    'data.backupDesc':    'Щотижнева резервна копія у хмарі',
    'data.exportTitle':   'Експорт даних',
    'data.exportDesc':    'Завантажте своє дерево у різних форматах',
    'data.importTitle':   'Імпорт',
    'data.importDesc':    'Завантажте існуюче дерево у форматі GEDCOM',
    'danger.title':       'Небезпечна зона',
    'danger.desc':        'Незворотні дії — будьте обережні',
    'danger.deleteTrees': 'Видалити всі дерева',
    'danger.deleteTreesDesc':'Усі ваші дерева та зв\'язки будуть видалені назавжди',
    'danger.deleteTreesBtn': 'Видалити дерева',
    'danger.logoutAll':   'Вийти з усіх пристроїв',
    'danger.logoutAllDesc':'Завершити всі активні сесії, крім поточної',
    'danger.logoutAllBtn':'Вийти скрізь',
    'danger.deleteAccount':'Видалити акаунт',
    'danger.deleteAccountDesc':'Акаунт та всі дані будуть видалені безповоротно',
    'danger.deleteAccountBtn':'Видалити акаунт',
    'modal.confirm':      'Підтвердіть дію',
    'modal.irreversible': 'Ця дія незворотна.',
    'btn.cancel':         'Скасувати',
    'btn.confirm':        'Підтвердити',
    'btn.save':           'Зберегти',
    'btn.apply':          'Застосувати',
    'btn.saveChanges':    'Зберегти зміни',
    'toast.profileSaved': 'Профіль збережено ✓',
    'toast.saved':        'Налаштування збережено ✓',
    'toast.loggedOut':    'Всі сесії завершено ✓',
    'toast.themeSaved':   'Тему «{name}» застосовано ✓',
    'toast.langSaved':    'Мову змінено на «{name}» ✓',
  },
  en: {
    'nav.logo':       'Rodo',
    'nav.logoSpan':   'vid',
    'nav.back':       '← Back to home',
    'nav.signin':     'Sign in',
    'nav.settings':   'Settings',
    'nav.myTree':     'My tree',
    'nav.treeList':   'My trees',

    'main.heroTitle':   'Preserve your family memory',
    'main.heroSub':     'Build your family tree, save photos and biographies, connect generations.',
    'main.btnCreate':   '🌱 Create tree',
    'main.btnMyTrees':  '🌿 My trees',
    'main.btnSignIn':   'Sign in',
    'main.feat1Title':  'Unlimited generations',
    'main.feat1Desc':   'Add as many ancestors and descendants as needed.',
    'main.feat2Title':  'Cloud storage',
    'main.feat2Desc':   'Your data is always safe and accessible from any device.',
    'main.feat3Title':  'Handy editor',
    'main.feat3Desc':   'Drag cards, add photos, connect relatives.',

    'signin.tabLogin':    'Sign in',
    'signin.tabRegister': 'Register',
    'signin.loginTitle':  'Welcome back 👋',
    'signin.loginSub':    'Sign in to continue working on your tree',
    'signin.email':       'Email address',
    'signin.password':    'Password',
    'signin.forgot':      'Forgot password?',
    'signin.btnLogin':    'Sign in',
    'signin.orDivider':   'or',
    'signin.googleLogin': 'Sign in with Google',
    'signin.regTitle':    'Create account 🌱',
    'signin.regSub':      'Start building your family tree today',
    'signin.name':        'Full name',
    'signin.email2':      'Email address',
    'signin.password2':   'Password',
    'signin.confirm':     'Confirm password',
    'signin.btnRegister': 'Register',
    'signin.googleReg':   'Register with Google',
    'signin.backLink':    '← Back',

    'nav.profile':        'Profile',
    'nav.appearance':     'Appearance',
    'nav.notifications':  'Notifications',
    'nav.privacy':        'Privacy',
    'nav.data':           'Data',
    'nav.danger':         'Danger zone',
    'page.title':         'Settings',
    'page.sub':           'Manage your account and personalise Rodovid',
    'profile.title':      'Profile',
    'profile.desc':       'Your name and personal information',
    'profile.firstName':  'First name',
    'profile.lastName':   'Last name',
    'profile.email':      'Email address',
    'profile.bio':        'About me',
    'profile.dob':        'Date of birth',
    'profile.phone':      'Phone',
    'profile.changePass': 'Change password',
    'profile.passHint':   'Leave blank if you don\'t want to change it',
    'profile.currentPass':'Current password',
    'profile.newPass':    'New password',
    'profile.confirmPass':'Confirm',
    'appear.title':       'Appearance',
    'appear.desc':        'Theme and interface language',
    'appear.themeLabel':  'Colour theme',
    'appear.langLabel':   'Interface language',
    'notif.title':        'Notifications',
    'notif.desc':         'Manage what and how you receive',
    'notif.email':        'Email notifications',
    'notif.emailDesc':    'Receive important updates by email',
    'notif.shared':       'New shared trees',
    'notif.sharedDesc':   'When someone invites you to a tree',
    'notif.changes':      'Member changes',
    'notif.changesDesc':  'When someone edits a shared tree',
    'notif.bday':         'Birthday reminders',
    'notif.bdayDesc':     'Notifications one day before a birthday',
    'notif.marketing':    'Marketing emails',
    'notif.marketingDesc':'Tips, news and product updates',
    'priv.title':         'Privacy',
    'priv.desc':          'Control who sees what',
    'priv.public':        'Public profile',
    'priv.publicDesc':    'Other users can find you in search',
    'priv.showDob':       'Show date of birth',
    'priv.showDobDesc':   'Visible to members of shared trees',
    'priv.invites':       'Allow invitations',
    'priv.invitesDesc':   'Others can invite you to trees',
    'priv.2fa':           'Two-factor authentication',
    'priv.2faDesc':       'Enhanced account security',
    'priv.visibility':    'Who can view your trees',
    'data.title':         'Data & export',
    'data.desc':          'Manage your data and trees',
    'data.autosave':      'Auto-save',
    'data.autosaveDesc':  'Automatically save changes every 5 minutes',
    'data.backup':        'Backups',
    'data.backupDesc':    'Weekly cloud backup',
    'data.exportTitle':   'Export data',
    'data.exportDesc':    'Download your tree in various formats',
    'data.importTitle':   'Import',
    'data.importDesc':    'Upload an existing tree in GEDCOM format',
    'danger.title':       'Danger zone',
    'danger.desc':        'Irreversible actions — be careful',
    'danger.deleteTrees': 'Delete all trees',
    'danger.deleteTreesDesc':'All your trees and connections will be deleted permanently',
    'danger.deleteTreesBtn': 'Delete trees',
    'danger.logoutAll':   'Log out of all devices',
    'danger.logoutAllDesc':'End all active sessions except the current one',
    'danger.logoutAllBtn':'Log out everywhere',
    'danger.deleteAccount':'Delete account',
    'danger.deleteAccountDesc':'Account and all data will be permanently deleted',
    'danger.deleteAccountBtn':'Delete account',
    'modal.confirm':      'Confirm action',
    'modal.irreversible': 'This action is irreversible.',
    'btn.cancel':         'Cancel',
    'btn.confirm':        'Confirm',
    'btn.save':           'Save',
    'btn.apply':          'Apply',
    'btn.saveChanges':    'Save changes',
    'toast.profileSaved': 'Profile saved ✓',
    'toast.saved':        'Settings saved ✓',
    'toast.loggedOut':    'All sessions ended ✓',
    'toast.themeSaved':   'Theme «{name}» applied ✓',
    'toast.langSaved':    'Language changed to «{name}» ✓',
  },
  de: {
    'nav.logo': 'Rodo', 'nav.logoSpan': 'vid',
    'nav.back': '← Zur Startseite', 'nav.signin': 'Anmelden',
    'nav.settings': 'Einstellungen', 'nav.myTree': 'Mein Baum',
    'nav.treeList': 'Meine Bäume',
    'main.heroTitle': 'Bewahren Sie die Erinnerung Ihrer Familie',
    'main.heroSub': 'Erstellen Sie einen Stammbaum, speichern Sie Fotos und Biografien.',
    'main.btnCreate': '🌱 Baum erstellen', 'main.btnMyTrees': '🌿 Meine Bäume', 'main.btnSignIn': 'Anmelden',
    'main.feat1Title': 'Unbegrenzte Generationen', 'main.feat1Desc': 'Fügen Sie so viele Vorfahren hinzu wie nötig.',
    'main.feat2Title': 'Cloud-Speicherung', 'main.feat2Desc': 'Ihre Daten sind sicher und überall zugänglich.',
    'main.feat3Title': 'Praktischer Editor', 'main.feat3Desc': 'Karten ziehen, Fotos hinzufügen, Verwandte verbinden.',
    'signin.tabLogin': 'Anmelden', 'signin.tabRegister': 'Registrieren',
    'signin.loginTitle': 'Willkommen zurück 👋', 'signin.loginSub': 'Melden Sie sich an, um weiterzumachen',
    'signin.email': 'E-Mail-Adresse', 'signin.password': 'Passwort',
    'signin.forgot': 'Passwort vergessen?', 'signin.btnLogin': 'Anmelden',
    'signin.orDivider': 'oder', 'signin.googleLogin': 'Mit Google anmelden',
    'signin.regTitle': 'Konto erstellen 🌱', 'signin.regSub': 'Beginnen Sie noch heute mit Ihrem Stammbaum',
    'signin.name': 'Vollständiger Name', 'signin.email2': 'E-Mail-Adresse',
    'signin.password2': 'Passwort', 'signin.confirm': 'Passwort bestätigen',
    'signin.btnRegister': 'Registrieren', 'signin.googleReg': 'Mit Google registrieren',
    'signin.backLink': '← Zurück',
    'page.title': 'Einstellungen', 'page.sub': 'Konto verwalten',
    'btn.cancel': 'Abbrechen', 'btn.confirm': 'Bestätigen', 'btn.save': 'Speichern',
    'btn.apply': 'Anwenden', 'btn.saveChanges': 'Änderungen speichern',
    'toast.profileSaved': 'Profil gespeichert ✓', 'toast.saved': 'Einstellungen gespeichert ✓',
    'toast.themeSaved': 'Thema «{name}» angewendet ✓', 'toast.langSaved': 'Sprache geändert zu «{name}» ✓',
    'appear.title': 'Erscheinungsbild', 'appear.desc': 'Thema und Sprache',
    'appear.themeLabel': 'Farbthema', 'appear.langLabel': 'Oberflächensprache',
  },
  pl: {
    'nav.logo': 'Rodo', 'nav.logoSpan': 'wód',
    'nav.back': '← Powrót', 'nav.signin': 'Zaloguj się',
    'nav.settings': 'Ustawienia', 'nav.myTree': 'Moje drzewo',
    'nav.treeList': 'Moje drzewa',
    'main.heroTitle': 'Zachowaj pamięć swojej rodziny',
    'main.heroSub': 'Buduj drzewo genealogiczne, zapisuj zdjęcia i biografie.',
    'main.btnCreate': '🌱 Utwórz drzewo', 'main.btnMyTrees': '🌿 Moje drzewa', 'main.btnSignIn': 'Zaloguj się',
    'main.feat1Title': 'Nieograniczone pokolenia', 'main.feat1Desc': 'Dodaj tylu przodków, ilu potrzebujesz.',
    'main.feat2Title': 'Przechowywanie w chmurze', 'main.feat2Desc': 'Twoje dane są bezpieczne i dostępne wszędzie.',
    'main.feat3Title': 'Wygodny edytor', 'main.feat3Desc': 'Przeciągaj karty, dodawaj zdjęcia, łącz krewnych.',
    'signin.tabLogin': 'Zaloguj się', 'signin.tabRegister': 'Rejestracja',
    'signin.loginTitle': 'Witaj z powrotem 👋', 'signin.loginSub': 'Zaloguj się, aby kontynuować pracę z drzewem',
    'signin.email': 'Adres e-mail', 'signin.password': 'Hasło',
    'signin.forgot': 'Zapomniałeś hasła?', 'signin.btnLogin': 'Zaloguj się',
    'signin.orDivider': 'lub', 'signin.googleLogin': 'Zaloguj przez Google',
    'signin.regTitle': 'Utwórz konto 🌱', 'signin.regSub': 'Zacznij budować swoje drzewo genealogiczne już dziś',
    'signin.name': 'Imię i nazwisko', 'signin.email2': 'Adres e-mail',
    'signin.password2': 'Hasło', 'signin.confirm': 'Potwierdź hasło',
    'signin.btnRegister': 'Zarejestruj się', 'signin.googleReg': 'Zarejestruj przez Google',
    'signin.backLink': '← Powrót',
    'page.title': 'Ustawienia', 'page.sub': 'Zarządzaj kontem',
    'btn.cancel': 'Anuluj', 'btn.confirm': 'Potwierdź', 'btn.save': 'Zapisz',
    'btn.apply': 'Zastosuj', 'btn.saveChanges': 'Zapisz zmiany',
    'toast.profileSaved': 'Profil zapisany ✓', 'toast.saved': 'Ustawienia zapisane ✓',
    'toast.themeSaved': 'Motyw «{name}» zastosowany ✓', 'toast.langSaved': 'Język zmieniony na «{name}» ✓',
    'appear.title': 'Wygląd', 'appear.desc': 'Motyw i język interfejsu',
    'appear.themeLabel': 'Motyw kolorów', 'appear.langLabel': 'Język interfejsu',
  },
};

// ════════════════════════════════════════════════════════════════════
// ПЕРЕКЛАДИ: застосувати до DOM
// ════════════════════════════════════════════════════════════════════

/** Повертає рядок перекладу для поточної мови. */
export function T(key) {
  const lang = localStorage.getItem('rodo-lang') || 'uk';
  return (i18n[lang] || i18n.uk)[key] ?? key;
}

/** Замінює textContent/placeholder/title елементів з data-i18n атрибутами. */
export function applyTranslations(lang) {
  const dict = i18n[lang] || i18n.uk;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (dict[key] !== undefined) el.textContent = dict[key];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    if (dict[key] !== undefined) el.placeholder = dict[key];
  });
  document.documentElement.lang = lang;
}

/** Зчитує збережену мову і застосовує переклади. */
export function applyStoredLang() {
  const lang = localStorage.getItem('rodo-lang') || 'uk';
  applyTranslations(lang);
}

applyStoredTheme();
applyStoredLang();